name: saem_talk_talk
description: "Saem Talk Talk"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  cupertino_will_pop_scope: ^1.2.1 #pop scope (스와이프 백 제스쳐 지원)
  flutter_svg: ^2.0.5 # SVG 아이콘
  fluttertoast: ^8.2.2 # 토스트
  flutter_easyloading: ^3.0.5
  gap: ^3.0.1 # 간격 위젯
  flutter_animate: ^4.5.2 # 간편 애니메이션 메소드 지원
  dropdown_button2: ^2.3.9 # dropdown 메뉴
  
  # 상태관리
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  flutter_hooks: ^0.21.2

  # 네트워크
  retrofit: ^4.4.2
  dio: ^5.8.0+1

  # 로컬 데이터베이스
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  flutter_secure_storage: ^9.2.4

  # 모델링
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  # DI
  get_it: ^8.0.3

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_analytics: ^12.0.0

  # 라우팅
  go_router: ^15.1.2

  #Utils
  flutter_dotenv: ^5.2.1
  permission_handler: ^12.0.0+1 #각종 플랫폼 권한 허용 및 감지
  easy_localization: ^3.0.0 # 다국어 지원
  infinite_scroll_pagination: ^4.1.0 # 무한스크롤 페이지네이션

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  retrofit_generator: ^7.0.8
  freezed: ^2.4.3
  go_router_builder: ^2.9.0
  hive_generator: ^2.0.1

flutter:
  assets:
    - .env
    - assets/svgs/
    - assets/svgs/common/
  
  uses-material-design: true
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900